"
I have names for different keyboard key. I am used to for compatibility reasons.
"
Class {
	#name : #KeyboardKey,
	#superclass : #Object,
	#category : #'WodenSceneGraph-MorphicSqueak'
}

{ #category : #'accessing' }
KeyboardKey class >> space [
	^ Character space
]

{ #category : #'accessing' }
KeyboardKey class >> A [
	^ $A
]


{ #category : #'accessing' }
KeyboardKey class >> B [
	^ $B
]


{ #category : #'accessing' }
KeyboardKey class >> C [
	^ $C
]


{ #category : #'accessing' }
KeyboardKey class >> D [
	^ $D
]


{ #category : #'accessing' }
KeyboardKey class >> E [
	^ $E
]


{ #category : #'accessing' }
KeyboardKey class >> F [
	^ $F
]


{ #category : #'accessing' }
KeyboardKey class >> G [
	^ $G
]


{ #category : #'accessing' }
KeyboardKey class >> H [
	^ $H
]


{ #category : #'accessing' }
KeyboardKey class >> I [
	^ $I
]


{ #category : #'accessing' }
KeyboardKey class >> J [
	^ $J
]


{ #category : #'accessing' }
KeyboardKey class >> K [
	^ $K
]


{ #category : #'accessing' }
KeyboardKey class >> L [
	^ $L
]


{ #category : #'accessing' }
KeyboardKey class >> M [
	^ $M
]


{ #category : #'accessing' }
KeyboardKey class >> N [
	^ $N
]


{ #category : #'accessing' }
KeyboardKey class >> O [
	^ $O
]


{ #category : #'accessing' }
KeyboardKey class >> P [
	^ $P
]


{ #category : #'accessing' }
KeyboardKey class >> Q [
	^ $Q
]


{ #category : #'accessing' }
KeyboardKey class >> R [
	^ $R
]


{ #category : #'accessing' }
KeyboardKey class >> S [
	^ $S
]


{ #category : #'accessing' }
KeyboardKey class >> T [
	^ $T
]


{ #category : #'accessing' }
KeyboardKey class >> U [
	^ $U
]


{ #category : #'accessing' }
KeyboardKey class >> V [
	^ $V
]


{ #category : #'accessing' }
KeyboardKey class >> W [
	^ $W
]


{ #category : #'accessing' }
KeyboardKey class >> X [
	^ $X
]


{ #category : #'accessing' }
KeyboardKey class >> Y [
	^ $Y
]


{ #category : #'accessing' }
KeyboardKey class >> Z [
	^ $Z
]
