Class {
	#name : #WDMetallicRoughnessMaterial,
	#superclass : #WDSurfaceMaterial,
	#instVars : [
		'baseColorFactor',
		'baseColorTexture',
		'emissionFactor',
		'emissionTexture',
		'normalTexture',
		'occlusionFactor',
		'occlusionTexture',
		'metallicFactor',
		'roughnessFactor',
		'metallicRoughnessTexture'
	],
	#category : #'WodenSceneGraph-Core-Material'
}

{ #category : #accessing }
WDMetallicRoughnessMaterial >> baseColorFactor [

	^ baseColorFactor
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> baseColorFactor: anObject [

	baseColorFactor := anObject
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> baseColorTexture [

	^ baseColorTexture
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> baseColorTexture: anObject [

	baseColorTexture := anObject
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> emissionFactor [

	^ emissionFactor
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> emissionFactor: anObject [

	emissionFactor := anObject
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> emissionTexture [

	^ emissionTexture
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> emissionTexture: anObject [

	emissionTexture := anObject
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> metallicFactor [

	^ metallicFactor
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> metallicFactor: anObject [

	metallicFactor := anObject
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> metallicRoughnessTexture [

	^ metallicRoughnessTexture
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> metallicRoughnessTexture: anObject [

	metallicRoughnessTexture := anObject
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> normalTexture [

	^ normalTexture
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> normalTexture: anObject [

	normalTexture := anObject
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> occlusionFactor [

	^ occlusionFactor
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> occlusionFactor: anObject [

	occlusionFactor := anObject
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> occlusionTexture [

	^ occlusionTexture
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> occlusionTexture: anObject [

	occlusionTexture := anObject
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> roughnessFactor [

	^ roughnessFactor
]

{ #category : #accessing }
WDMetallicRoughnessMaterial >> roughnessFactor: anObject [

	roughnessFactor := anObject
]
