Class {
	#name : 'WDModelAnimationSubtreeChannelMap',
	#superclass : 'Object',
	#instVars : [
		'subtreeMap',
		'targets'
	],
	#category : 'WodenSceneGraph-Core-Animation',
	#package : 'WodenSceneGraph-Core',
	#tag : 'Animation'
}

{ #category : 'accessing' }
WDModelAnimationSubtreeChannelMap >> subtreeMap [

	^ subtreeMap
]

{ #category : 'accessing' }
WDModelAnimationSubtreeChannelMap >> subtreeMap: anObject [

	subtreeMap := anObject
]

{ #category : 'accessing' }
WDModelAnimationSubtreeChannelMap >> targets [

	^ targets
]

{ #category : 'accessing' }
WDModelAnimationSubtreeChannelMap >> targets: anObject [

	targets := anObject
]
